SUBREDDIT_MAPPING = {
    "Celtics": "bostonceltics",
    "Nets": "GoNets",
    "Knicks": "NYKnicks",
    "76ers": "sixers",
    "Raptors": "torontoraptors",
    "Hawks": "AtlantaHawks",
    "Hornets": "CharlotteHornets",
    "Heat": "heat",
    "Magic": "OrlandoMagic",
    "Wizards": "washingtonwizards",
    "Warriors": "warriors",
    "Clippers": "LAClippers",
    "Lakers": "lakers",
    "Suns": "suns",
    "Kings": "kings",
    "Bulls": "chicagobulls",
    "Cavaliers": "clevelandcavs",
    "Pistons": "DetroitPistons",
    "Pacers": "pacers",
    "Bucks": "MkeBucks",
    "Nuggets": "denvernuggets",
    "Timberwolves": "timberwolves",
    "Thunder": "Thunder",
    "Trail Blazers": "ripcity",
    "Jazz": "UtahJazz",
    "Mavericks": "Mavericks",
    "Rockets": "rockets",
    "Grizzlies": "memphisgrizzlies",
    "Pelicans": "NOLAPelicans",
    "Spurs": "NBASpurs",
}
